Show a badge for embargoed works in dashboard and search results
psu-libraries/scholarsphere pull request #1019
Opened 2021-05-12 18:46 UTC by nicktiberi

Fixes #441.

If a work is embargoed, we now display an embargoed badge instead of the normal access level badge in the search results.

On the work details, we display the normal access level badge because there is a more detailed embargoed message on that page.

### Dashboard
<img width="972" alt="Screen Shot 2021-05-12 at 2 00 32 PM" src="https://user-images.githubusercontent.com/639920/118028015-94babc00-b330-11eb-8233-3d61376425dc.png">

### Work Details
<img width="2521" alt="Screen Shot 2021-05-12 at 2 00 47 PM" src="https://user-images.githubusercontent.com/639920/118028049-9e442400-b330-11eb-98cf-a41cb7260492.png">

2021-05-12 18:49 UTC, nicktiberi commented on app/decorators/resource_decorator.rb
> +
@awead - I don't love declaring a second method for the visibility badge, but wasn't sure if there was a way to pass the `mini` flag into the resource decorator and conditionally set it in the `visibility_badge` method above.

2021-05-13 13:10 UTC, awead requested changes
We can pair over these if it's confusing.

2021-05-13 13:10 UTC, awead commented on app/decorators/resource_decorator.rb
> +
I think this is stemming from the fact that we only want the embargo badge to show in search results, which are use the mini component? We should revisit this decision...

2021-05-13 13:10 UTC, awead commented on app/models/solr_document.rb
> +  end
I think I would opt for two methods here to reduce the if-y-ness:

``` ruby
def embargoed_until
  Time.zone.parse(self.fetch(:embargoed_until_dtsi, ''))
rescue ArgumentError
end
```
The `fetch` method will take a default value. This is handy when dealing with null values in hashes. In this case, we can return an empty string, which Time will evaluate to nill. The rescue handles the other cases. Ex:

```
> Time.zone.parse('')
=> nil
> Time.zone.parse('asdf')
=> nil
> Time.zone.parse('2002')
ArgumentError: argument out of range
```

Then, our `embargoed?` method becomes a lot simpler:

``` ruby
def embargoed?
  return false if embargoed_until.nil?

   embargoed_until > Time.zone.now
end
```

2021-05-13 13:10 UTC, awead commented on app/components/visibility_badge_component.rb
>      end
I think you should be able to keep icon, label, and html_class methods the same by using the visibility and details methods:

``` ruby
def visibility
  'embargo' if work.embargoed?

  work.visibility || Permissions::Visibility::PRIVATE 
end

def details
  {
    'embargo' => {
      label: i18n_label('embargoed'),
      color: 'red',
      icon: 'lock_clock'
...
```

We are conflating visibility and embargo here, which is probably ok within the context of just this one component. However, I could also renaming the visibility method to `details_key` or just `key` for clarity.

2021-05-13 13:49 UTC, nicktiberi commented on app/decorators/resource_decorator.rb
> +
Per our conversation with Seth in standup, we are going to show the embargoed badge everywhere and not make a distinction between the mini and non-mini version.

2021-05-13 14:44 UTC, nicktiberi commented
@awead - I forgot to add the tooltip. 🤦 Please hold off on re-reviewing until I get that in. Should be a pretty quick change.

2021-05-13 15:02 UTC, awead approved these changes, later dismissed

2021-05-13 15:06 UTC, nicktiberi commented
@awead - OK - ready to go now, tooltip and all!

2021-05-13 17:08 UTC, awead approved these changes
Nicely done!

2021-05-13 17:08 UTC, merged