Updates to deposited and published dates display in metadata component
psu-libraries/scholarsphere pull request #1033
Opened 2021-05-17 19:29 UTC by nicktiberi

- Deposited date no longer shows time
- Publication date is now also shown on the mini component

### Before
<img width="987" alt="Screen Shot 2021-05-17 at 3 28 39 PM" src="https://user-images.githubusercontent.com/639920/118545444-99aeaf80-b724-11eb-8455-04545e888800.png">

### After
<img width="968" alt="Screen Shot 2021-05-17 at 3 26 06 PM" src="https://user-images.githubusercontent.com/639920/118545454-9d423680-b724-11eb-8e8e-fd9cc1a62713.png">

2021-05-17 20:47 UTC, awead commented
I think this looks good, but wanted to get @srerickson opinion. I'm not sure about showing _both_ dates.

2021-05-18 14:49 UTC, srerickson commented
I can't make up my mind on the publication date and I think we'll need to a complete redesign of the card to figure it out. For now, let's remove the "Publication Date" table row. I'll start a separate issue for redesigning the card.

2021-05-18 14:51 UTC, srerickson requested changes
Let's remove the Publication Date from the component.

2021-05-18 17:43 UTC, awead approved these changes

2021-05-18 18:30 UTC, merged