Removed DoiSchema from WorkVersion's #document_builder.
psu-libraries/scholarsphere pull request #1180
Opened 2022-01-20 21:13 UTC by ajkiessl

After fiddling around with Solr + Blacklight and realizing I needed to reindex Solr, and after chatting with Seth, it looks like all I had to do was remove one line from `WorkVersion`.  By removing `DoiSchema` from `WorkVersion`'s `#document_builder`, `WorkVersion`s will no longer be a part of the query `DoiSearch` uses to return UUIDs matched to DOIs.  Only `Work`s and `Collection`s are included now.

2022-01-21 13:51 UTC, ajkiessl commented
After thinking about this a little more, I need to find a way the identify any WorkVersions that have a DOI but their Work does not.  I'm going to have to make some changes, so this isn't quite ready for review.

2022-01-21 19:25 UTC, ajkiessl commented
This is ready to go.

2022-01-24 13:56 UTC, nicktiberi approved these changes, later dismissed
This looks good to me, @ajkiessl!

@rschenk - would you mind taking a quick look at this as well?

2022-01-24 16:03 UTC, rschenk requested changes
I think I figured out a way to do the implementation that avoids the `WorkVersion` specific code in the concern (and in fact requires no changes at all to `all_dois.rb` file). See what you think...

2022-01-24 16:03 UTC, rschenk commented on spec/models/concerns/all_dois_spec.rb
> +      let!(:work) { create :work, versions_count: 2, has_draft: false }
Because we are using FactoryBot here, we need to change the line at the top of the file from `require 'spec_helper'` to `require 'rails_helper'` (I can't make a comment on that line because it didn't change)

2022-01-24 16:03 UTC, rschenk commented on app/models/concerns/all_dois.rb
> +    end
This method adds some class-specific code and creates a two-directional dependency here, which I am not crazy about. But there is another way: Roll back all changes in `all_dois.rb` and instead override `all_dois` inside the `WorkVersion` class.

2022-01-24 16:03 UTC, rschenk commented on app/models/work_version.rb
> +
There are two changes we can do here.

First is an easy one, `work.fields_with_dois.map { |field| work.send(field).present? }.include?(true)` basically just re-implements `#all_dois` so we can change this to `work.all_dois.any?`

The second thing we can do is delete this method, but use the logic that you wrote to override `#all_dois` for `WorkVersion` like so:

```ruby
class WorkVersion < ApplicationRecord
  # ...

  def all_dois
    return [] if !latest_published_version? || 
                   (latest_published_version? && work.all_dois.any?)

    super
  end

 #...
end

```

2022-01-24 17:48 UTC, rschenk approved these changes
🥳 🎉

2022-01-24 17:51 UTC, merged