WIP: Create Curator to Depositor Ticket
psu-libraries/scholarsphere pull request #1490
Opened 2024-02-19 15:35 UTC by ajkiessl

2024-02-20 17:37 UTC, EricDurante requested changes
Looks good overall. Had a few questions and suggestions for potential changes.

2024-02-20 17:37 UTC, EricDurante commented on app/controllers/admin/create_curation_ticket_controller.rb
> +  class CreateCurationTicketController < ApplicationController
Just wondering about the naming here. Can we foresee any other actions that ScholarSphere might perform on LibAnswers tickets? Would it make more sense for this to be `CurationTicketsController` with a `#create` action?

2024-02-20 17:37 UTC, EricDurante commented on app/services/libanswers_api_service.rb
> +      "ScholarSphere Deposit Curation: #{work.versions.last.title}"
Refactoring suggestion:  replace `work.versions.last` with `work.latest_version`.

2024-02-20 17:37 UTC, EricDurante commented on app/services/libanswers_api_service.rb
> +      work.depositor.email
Refactoring suggestion:  I think it would be better to have the work delegate to its depositor to access `email` and `display_name`.

2024-02-20 17:37 UTC, EricDurante commented on spec/features/dashboard/work_settings_spec.rb
> +            # a routing error will be raised in the test env.  Rescue it and check the correct redirect location
Yeah, I've done exactly this sort of thing before.

2024-02-20 17:37 UTC, EricDurante commented on spec/features/dashboard/work_settings_spec.rb
Just wondering - is it possible to have one test that exercises the live integration with LibAnswers? Like, could we create a separate ticket queue in LibAnswers that's just for testing or some such thing? Normally I'd suggest trying to do something like that if possible, but since this is an admin-facing feature with relatively few users, any accidental breakage would be low-risk.

So I'd say that if it's possible/easy to do, then it's maybe worth it. Otherwise, never mind.

2024-02-20 19:27 UTC, ajkiessl commented on app/controllers/admin/create_curation_ticket_controller.rb
> +  class CreateCurationTicketController < ApplicationController
Hmm yeah potentially.  The #submit action was leftover from when I had this as a form, so I think I will change it to the way you say. While there isn't anything in the works, I could maybe see listing tickets for a work, or maybe giving admins the capability to update or delete tickets straight from ScholarSphere. Other than that, the depositor contacting curators feature  ( #1465 ) will use the LibAnswers API.  However, that one won't be within the Admin module.  I guess we could move the controller out of the Admin module and have a before action do some kind of authentication on the action the creates tickets from the curator to depositor perspective?

2024-02-20 19:36 UTC, ajkiessl commented on spec/features/dashboard/work_settings_spec.rb
If there's a way to create a test queue that doesn't notify admins when a ticket is created, then I would say yes, there's definitely a way to do this.  I can check with Briana to see if this is possible.

2024-02-20 19:42 UTC, ajkiessl commented on spec/features/dashboard/work_settings_spec.rb
Actually, the max number of queues is 10 and we already have 10

2024-02-20 19:49 UTC, ajkiessl commented on spec/features/dashboard/work_settings_spec.rb
If the test is kept out of the regularly running test suite, and only ran manually when needed, I don't think there would be a problem creating a test that does the full integration into the ScholarSphere queue.  We'd want to make sure the contents are clear it is a test ticket and can be deleted, though.

2024-02-20 20:55 UTC, EricDurante commented on spec/features/dashboard/work_settings_spec.rb
Hmm. I can't say that I like the idea of automated tests doing things to a production system, and definitely not without some kind of clear separation of permissions and/or data. It's maybe not so bad as long as it's only doing non-destructive things, but it may not stay that way forever.

I'd say let's shelve this idea for now until there's a better way to do it.

2024-02-21 02:02 UTC, EricDurante approved these changes
Changes look good!

2024-02-21 14:19 UTC, merged